
spring:
  datasource:
    url: jdbc:mysql://110.42.150.65:3306/movie_star
    username: dw
    password: dw
    driver-class-name: com.mysql.cj.jdbc.Driver


  #    hive:
  #      url: jdbc:hive2://101.132.43.76:10000/movie
  #      driver-class-name: org.apache.hive.jdbc.HiveDriver
  #      type: com.alibaba.druid.pool.DruidDataSource
  #      user: root
  #      password: ZJ010821lmx
  #      initialSize: 1
  #      minIdle: 3
  #      maxActive: 202
  #      maxWait: 60000
  #      timeBetweenEvictionRunsMillis: 60000
  #      minEvictableIdleTimeMillis: 30000
  #      validationQuery: select 1
  #      testWhileIdle: true
  #      testOnBorrow: false
  #      testOnReturn: false
  #      poolPreparedStatements: true
  #      maxPoolPreparedStatementPerConnectionSize: 20
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: dw



#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: org.neo4j.jdbc.bolt.BoltDriver
#    url: jdbc:neo4j:bolt://localhost:7687
#    username: neo4j
#    password: root
#    #   ???????
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    #    validation-query: match (n) return id(n) limit 2
#    testWhileIdle: false
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    filters: stat,wall,log4j
#    maxPoolPreparedStatementPerConnectionSize: 20
#    useGlobalDataSourceStat: true
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

server:
  port : 8004


