
spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: org.neo4j.jdbc.bolt.BoltDriver
#    url: jdbc:neo4j:bolt://localhost:7687
#    username: neo4j
#    password: root
#    #   ???????
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    #    validation-query: match (n) return id(n) limit 2
#    testWhileIdle: false
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    filters: stat,wall,log4j
#    maxPoolPreparedStatementPerConnectionSize: 20
#    useGlobalDataSourceStat: true
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: dw

server:
  port : 8004

#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database: mysql
#    show-sql: true


